spring:
  application:
    name: HappyFarmersMarket
  datasource:
    url: jdbc:postgresql://localhost:5432/happyfarmersmarket
    username: happyfarmersmarket
    password: freshproduce!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

argon2:
  saltLength: 12
  hashLength: 32
  parallelism: 1
  memory: 65536
  iterations: 8

